[package]
name = "escrow"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
solana-program = "=1.7.11"
thiserror = "1.0.30"
spl-token = {version = "3.2.0", features = ["no-entrypoint"]}
arrayref = "0.3.6"

[features]
test-bpf = []
no-entrypoint = []

[dev-dependencies]
solana-program-test = "=1.7.11"
solana-sdk = "=1.7.11"

[lib]
crate-type = ["cdylib", "lib"]
