[package]
name = "transfer-lamports"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []
trace-compute=[]

[dependencies]
solana-program = "1.8.0"

[dev-dependencies]
solana-program-test = "1.8.0"
solana-sdk = "1.8.0"

[lib]
crate-type = ["cdylib", "lib"]
